const completeConcentrationsList = [
  "Yet To Declare",
  "Independent Concentration - AB",
  "Independent Concentration - SCB",
  "American Studies - AB",
  "Anthropology - AB (Anthropological Archaeology)",
  "Anthropology - AB (Biological Anthropology)",
  "Anthropology - AB (General Anthropology)",
  "Anthropology - AB (Linguistic Anthropology)",
  "Anthropology - AB (Medical Anthropology)",
  "Anthropology - AB (Socio-cultural Anthropology)",
  "Applied Mathematics - AB",
  "Applied Mathematics - SCB",
  "Applied Mathematics-Biology - SCB",
  "Applied Mathematics-Computer Science - SCB",
  "Applied Mathematics-Economics - AB (Advanced Economics)",
  "Applied Mathematics-Economics - AB (Mathematical Finance)",
  "Applied Mathematics-Economics - SCB (Advanced Economics)",
  "Applied Mathematics-Economics - SCB (Mathematical Finance)",
  "Archaeology & Ancient World - AB",
  "Architecture - AB",
  "Astronomy - AB",
  "Behavioral Decision Sciences - AB",
  "Biochemistry & Molecular Biology - SCB",
  "Biology - AB",
  "Biology - SCB",
  "Biomedical Engineering - SCB",
  "Biophysics - SCB",
  "Business, Entrepreneurship and Organizations - AB (Business Economics)",
  "Business, Entrepreneurship and Organizations - AB (Entrepreneurship & Tech Mgmt)",
  "Business, Entrepreneurship and Organizations - AB (Organizational Studies)",
  "Chemical Physics - SCB",
  "Chemistry - AB",
  "Chemistry - SCB",
  "Chemistry - SCB (Chemical Biology)",
  "Chemistry - SCB (Materials)",
  "Classics - AB",
  "Classics - AB (Greek and Latin)",
  "Classics - AB (Greek and Sanskrit)",
  "Classics - AB (Greek)",
  "Classics - AB (Latin and Sanskrit)",
  "Classics - AB (Latin)",
  "Classics - AB (Sanskrit)",
  "Classics - AB (South Asian Classics)",
  "Cognitive Neuroscience - AB",
  "Cognitive Neuroscience - SCB",
  "Cognitive Science - AB",
  "Cognitive Science - SCB",
  "Comparative Literature - AB (Literary Translation)",
  "Comparative Literature - AB (Literature in Three Languages)",
  "Comparative Literature - AB (Literature in Two Languages)",
  "Computational Biology - AB",
  "Computational Biology - SCB",
  "Computer Science - AB",
  "Computer Science - SCB",
  "Computer Science-Economics - AB",
  "Computer Science-Economics - SCB",
  "Contemplative Studies - AB (Humanities)",
  "Contemplative Studies - AB (Sciences)",
  "Development Studies - AB",
  "Early Modern World - AB",
  "East Asian Studies - AB",
  "Economics - AB",
  "Economics - AB (Business Economics)",
  "Education Studies - AB",
  "Egyptology & Assyriology - AB (Assyriology)",
  "Egyptology & Assyriology - AB (Egyptology)",
  "Engineering - AB",
  "Engineering - SCB (Chemical)",
  "Engineering - SCB (Computer)",
  "Engineering - SCB (Electrical)",
  "Engineering - SCB (Environmental)",
  "Engineering - SCB (Materials)",
  "Engineering - SCB (Mechanical)",
  "Engineering and Physics - SCB",
  "English - AB",
  "Environmental Science - SCB",
  "Environmental Studies - AB",
  "Ethnic Studies - AB",
  "French & Francophone Studies - AB",
  "Gender & Sexuality Studies - AB",
  "Geological Sciences - AB",
  "Geological Sciences - SCB",
  "Geology - Biology - AB",
  "Geology - Biology - SCB",
  "Geology - Chemistry - AB",
  "Geology - Chemistry - SCB",
  "Geology - Physics/Mathematics - AB",
  "Geology - Physics/Mathematics - SCB",
  "Health and Human Biology - AB",
  "Hispanic Literatures and Cultures - AB",
  "History - AB",
  "History of Art and Architecture - AB",
  "History of Art and Architecture - AB (Architectural Studies)",
  "International Relations - AB (Political Economy and Society)",
  "International Relations - AB (Security and Society)",
  "International and Public Affairs - AB (Development)",
  "International and Public Affairs - AB (Policy and Governance)",
  "International and Public Affairs - AB (Security)",
  "Italian Studies - AB",
  "Judaic Studies - AB",
  "Latin American & Caribbean Studies - AB",
  "Linguistics - AB",
  "Linguistics - SCB",
  "Literary Arts - AB",
  "Mathematics - AB",
  "Mathematics - SCB",
  "Mathematics-Computer Science - SCB",
  "Mathematics-Economics - AB",
  "Medieval Cultures - AB",
  "Medieval Cultures - AB (Late Antique Cultures)",
  "Middle Eastern Studies - AB",
  "Modern Culture and Media - AB (Track I)",
  "Modern Culture and Media - AB (Track II)",
  "Music - AB",
  "Neuroscience - SCB",
  "Philosophy - AB",
  "Physics - AB",
  "Physics - AB (Mathematical)",
  "Physics - SCB",
  "Physics - SCB (Astrophysics)",
  "Physics - SCB (Biological)",
  "Physics - SCB (Mathematical)",
  "Physics and Philosophy - AB",
  "Political Science - AB",
  "Portuguese and Brazilian Studies - AB",
  "Psychology - AB",
  "Psychology - SCB",
  "Public Health - AB",
  "Public Policy - AB",
  "Religious Studies - AB",
  "Science, Technology, and Society - AB",
  "Slavic Studies - AB",
  "Social Analysis and Research - SCB",
  "Sociology - AB",
  "Sociology - AB (Organizational Studies)",
  "South Asian Studies - AB",
  "Statistics - SCB",
  "Theatre Arts & Performance Studies - AB (Dance)",
  "Theatre Arts & Performance Studies - AB (Performance Studies)",
  "Theatre Arts & Performance Studies - AB (Theatre Arts)",
  "Urban Studies - AB",
  "Visual Arts - AB",
];

export default completeConcentrationsList;
